CREATE DATABASE BDUSERS;
USE BDUSERS;

CREATE TABLE usuarios(
	IDUSER INT PRIMARY KEY,
    NOMBRE VARCHAR(70) NOT NULL,
    APELLIDOS VARCHAR(70) NOT NULL,
    EMAIL VARCHAR(70) NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL
);
    
